server:
  port: 8082

spring:
  application:
    name: strategy-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/algotrading?ssl=false
    username: algotrading
    password: algotrading
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# Strategy Configuration
strategy:
  execution:
    enabled: true
    interval: 60000 # 1 minute in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
